project:
  type: website

website:
  navbar:
    title: "Caddy"
    background: "#f8f9fa"
    search: true
    tools:
    - icon: twitter
      href: https://twitter.com/i_dot_ai
    - icon: github
      href: https://github.com/i-dot-ai/caddy_chatbot
  title: "Caddy"
  page-navigation: true
  repo-url: https://github.com/i-dot-ai/caddy_chatbot
  repo-actions: [edit, issue]
  sidebar:
    logo: docs/assets/caddy.png
    style: "docked"
    contents: docs

format:
  html:
    toc: true

execute:
  freeze: "auto"
